volumes:
  mariadb-10.11:
    external: false
    name: mariadb-10.11

services:
  mariadb-10.11:
    image: mariadb:10.11
    restart: always
    volumes:
      - mariadb-10.11:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_ROOT_PASSWORD=oneinstack
    network_mode: host
    container_name: mariadb-10.11
