volumes:
  mariadb-10.6:
    external: false
    name: mariadb-10.6

services:
  mariadb-10.6:
    image: mariadb:10.6
    restart: always
    volumes:
      - mariadb-10.6:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_ROOT_PASSWORD=oneinstack
    network_mode: host
    container_name: mariadb-10.6
