volumes:
  mariadb-10.5:
    external: false
    name: mariadb-10.5

services:
  mariadb-10.5:
    image: mariadb:10.5
    restart: always
    volumes:
      - mariadb-10.5:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_ROOT_PASSWORD=oneinstack
    network_mode: host
    container_name: mariadb-10.5
