volumes:
  mariadb:
    external: false
    name: mariadb

services:
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_ROOT_PASSWORD=oneinstack
    network_mode: host
    container_name: mariadb
