volumes:
  mariadb-10.11:
    external: false
    name: mariadb-10.11

services:
  mariadb-10.11:
    image: mariadb:10.11
    restart: always
    volumes:
      - mariadb-10.11:/var/lib/mysql
    hostname: mariadb-10.11
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    container_name: mariadb-10.11
