volumes:
  mariadb-10.5:
    external: false
    name: mariadb-10.5

services:
  mariadb-10.5:
    image: mariadb:10.5
    restart: always
    volumes:
      - mariadb-10.5:/var/lib/mysql
    hostname: mariadb-10.5
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    container_name: mariadb-10.5
