volumes:
  mariadb-11.4:
    external: false
    name: mariadb-11.4

services:
  mariadb-11.4:
    image: mariadb:11.4
    restart: always
    volumes:
      - mariadb-11.4:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_ROOT_PASSWORD=oneinstack
    network_mode: host
    container_name: mariadb-11.4
