volumes:
  mongodb-8.0:
    external: false
    name: mongodb-8.0

services:
  mongodb-8.0:
    image: mongo:8.0
    restart: always
    volumes:
      - mongodb-8.0:/data/db
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=oneinstack
    network_mode: host
    container_name: mongodb-8.0
