volumes:
  mysql-8.0:
    external: false
    name: mysql-8.0

services:
  mysql-8.0:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql-8.0:/var/lib/mysql
    hostname: mysql-8.0
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    container_name: mysql-8.0
