volumes:
  mysql-8.0:
    external: false
    name: mysql-8.0

services:
  mysql-8.0:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql-8.0:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=oneinstack
    network_mode: host
    container_name: mysql-8.0
