volumes:
  mysql-8.4:
    external: false
    name: mysql-8.4

services:
  mysql-8.4:
    image: mysql:8.4
    restart: always
    volumes:
      - mysql-8.4:/var/lib/mysql
    hostname: mysql-8.4
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    container_name: mysql-8.4
