volumes:
  mysql-8.4:
    external: false
    name: mysql-8.4

services:
  mysql-8.4:
    image: mysql:8.4
    restart: always
    volumes:
      - mysql-8.4:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=oneinstack
    network_mode: host
    container_name: mysql-8.4
