services:
  nginx:
    image: openresty/openresty:latest
    cap_add:
      - BPF
      - NET_ADMIN
    command: openresty -c /etc/nginx/nginx.conf -g 'deamon off;'
    restart: always
    volumes:
      - /etc/nginx:/etc/nginx
      - /data/wwwlogs:/data/wwwlogs
      - /data/wwwroot:/data/wwwroot
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    container_name: nginx
