services:
  php-8.2-fpm:
    image: closehandle/php:8.2-fpm
    restart: always
    volumes:
      - /data/wwwroot:/data/wwwroot
    hostname: php-8.2-fpm
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
    container_name: php-8.2-fpm
