services:
  php-7.4-fpm:
    image: closehandle/php:7.4-fpm
    restart: always
    volumes:
      - /data/wwwroot:/data/wwwroot
    environment:
      - TZ=Asia/Shanghai
      - FPM_BIND=127.0.0.1
      - FPM_PORT=9000
    network_mode: host
    container_name: php-7.4-fpm
