volumes:
  postgresql-13:
    external: false
    name: postgresql-13

services:
  postgresql-13:
    image: postgres:13
    restart: always
    volumes:
      - postgresql-13:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    network_mode: host
    container_name: postgresql-13
