volumes:
  postgresql-12:
    external: false
    name: postgresql-12

services:
  postgresql-12:
    image: postgresql:12
    restart: always
    volumes:
      - postgresql-12:/var/lib/postgresql/data
    hostname: postgresql-12
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    container_name: postgresql-12
