volumes:
  postgresql-14:
    external: false
    name: postgresql-14

services:
  postgresql-14:
    image: postgres:14
    restart: always
    volumes:
      - postgresql-14:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    network_mode: host
    container_name: postgresql-14
