volumes:
  postgresql-16:
    external: false
    name: postgresql-16

services:
  postgresql-16:
    image: postgres:16
    restart: always
    volumes:
      - postgresql-16:/var/lib/postgresql/data
    hostname: postgresql-16
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    container_name: postgresql-16
