volumes:
  postgresql:
    external: false
    name: postgresql

services:
  postgresql:
    image: postgresql:latest
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
    hostname: postgresql
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    container_name: postgresql
