volumes:
  postgresql-15:
    external: false
    name: postgresql-15

services:
  postgresql-15:
    image: postgres:15
    restart: always
    volumes:
      - postgresql-15:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    network_mode: host
    container_name: postgresql-15
