volumes:
  postgresql:
    external: false
    name: postgresql

services:
  postgresql:
    image: postgres:latest
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    network_mode: host
    container_name: postgresql
