volumes:
  postgresql-12:
    external: false
    name: postgresql-12

services:
  postgresql-12:
    image: postgres:12
    restart: always
    volumes:
      - postgresql-12:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    network_mode: host
    container_name: postgresql-12
