volumes:
  postgresql-14:
    external: false
    name: postgresql-14

services:
  postgresql-14:
    image: postgresql:14
    restart: always
    volumes:
      - postgresql-14:/var/lib/postgresql/data
    hostname: postgresql-14
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    container_name: postgresql-14
