volumes:
  postgresql-18:
    external: false
    name: postgresql-18

services:
  postgresql-18:
    image: postgres:18
    restart: always
    volumes:
      - postgresql-18:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    network_mode: host
    container_name: postgresql-18
