volumes:
  postgresql-15:
    external: false
    name: postgresql-15

services:
  postgresql-15:
    image: postgresql:15
    restart: always
    volumes:
      - postgresql-15:/var/lib/postgresql/data
    hostname: postgresql-15
    networks:
      - oneinstack
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=oneinstack
    container_name: postgresql-15
